### ISSUE TITLE
Some users are getting error failed to load component while navigating thru the resource pages on LP

### ISSUE THREAD

**Issue by roseliafunes** [msft-teams/tools#62]
The issue persist if LP is accessed thru the browser (Chrome or Edge) or thru Teams, it also happens in multiple resources, site permissions changes does not fix the issue.
<img width="528" alt="lperror" src="https://user-images.githubusercontent.com/77993667/144514389-12be9a06-b230-4bfa-87db-ef51ea9ac5b6.png">

**Comment by vicslive** [comment]
error text from pic.
Something went wrong 
If the problem persists. contact the site administrator and give them the information in Technical Details. 
DE-rms 
l: 
Failed to load component "141d4ab7-b6ca-4bf4—acS9-25b7bf93642d- (CustomLearningWebPart). Original error: Failed to load path dependency -M36SLPStrings• from component 
-141d4ab7.b6ca.4bf4.aeS9.25b7bf93642d" (CustomLearningWebPart). Original error•. Error loading https://eomponent.id.InvaIId/141d4ab7.b6ea.4bf4.ae59. 
25b7bf93642d_4.1.3/M365LPStrinøs 
Unable to load script https://yumbrandsinc-sharepoint.com/sites/apps_cataIogfClientSideAssets/26c9cd9f.db62.49bI -b102-7fOdad281eaO/webpart.m3651pstrings_en- 
INNERERROR: 
Failed to load path dependency • M36SLPStrings• from component "141d4ab7.b6ea.4bf4.ae59.25b7bf93642d• (CustomLearningWebPart). Original error: Error loading 
https://component-id.invalid/141d4ab7.b6ca-4bf4..c59-25b7bf93642d_4.1.3/M365LPStrings 
Unable to I O.ad script https://yumbrandsincsharep0int.com/sites/apps_catalogfClicntSideAssets/26c9cd9f.db62.49bl -b102-7fOdad281eaO/webpart.m3651pstrings_en- 
us Sebf05e875%e5efe5e691d313907759.js 
CALLSTACK: 
at t (as constructor) (https://modernb.akamai.odsp.edn.office.net/files/sp.client/sp.pages.assembly emus 
at new t (https://modernb.akamai.odsp.cdn.office.net/fiIes/sp-cIient/sp.pages.assembty_en.us_538e4fe3e5278b807430f5cecedOcc12.js:71:9102) 
at Function.e.buiIdErrorWithVerboseLog (https://modernb.akamai.odsp.cdn.office.net/files/sp.client/sp.pages.assembly_en-us_S38e4fe3e5278b807430f5cecedOcc12.js:71:46302) 
at Function.e.buildLoadComponentError (https://modernb.akamai.odsp.edn.office.net/files/sp.elient/sp.pages.assembly emus 
at https:f/modernb.akamai.odsp.cdn.office.net/files/sp-client/chunk.systemjs.component-loader_en-us_f4c50512041400f60c91 .js:l :65943
